//HOMEPAGE
export const TITOLO_NEWS = "I PARCHI ITALINI I PIU PREMIATI IN EUROPA PER IL TURISMO SOSTENIBILE";
export const TESTO = "Lorem ipsum dolor sit amet, consectetur adipisci elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim " +
    "ad minim veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur. ";
export const NEWS="Scopri le ultime novita riguardo parchi e aree marine protette"
export const TROVA_AREA="Trova un area";
export const COLORE_BLUE="#13638c";
export const COLORE_VERDE="#03a550";
export const COLORE_VERDE_TRASPARENTE="rgba(3,165,80,0.6)";
export const COLORE_BIANCO="white";
export const COLORE_CELESTE="#2A9DD2";
export const COLORE_CELESTE_TRASPARENTE="rgba(42,157,210,0.6)";
export const COLORE_VIOLA = "#EC85AC";
export const COLORE_VIOLA_TRASPARENTE = "rgba(236,133,172,0.5)";
export const COLORE_ROSSO = "#910000";
export const COLORE_ARANCIO_CHIARO ="#FFF9EF";
export const COLORE_GRIGIO_CHIARO = "#F4F4F4";
export const COLORE_VERDE_CHIARO = "#e7ffda";
export const COLORE_VIOLA_CHIARO = "#FFF6F9";
export const COLORE_ARANCIONE_CHIARO = "rgba(255,161,116,0.74)";
export const COLORE_ARANCIONE = "#ff7f3e";
export const AREA_PARCO="PN";
export const AREA_MARINA="AMP";
export const TESTO_AREA_PARCO="ESPLORA I PARCHI NAZIONALI E LE AREE NATURALI PROTETTE";
export const TESTO_AREA_MARINA="ESPLORA LE AREE MARINE PROTETTE";
export const TESTO2_AREA_PARCO="SELEZIONA UNO DEI 24 PARCHI PER SAPERNE DI PIÙ";
export const TESTO3_AREA="In Italia esistono 871 aree protette, per un totale di oltre 3 milioni di ettari tutetati a terra, circa 2.850mila ettari a mare e 658 chilometri di costa.";
export const TESTO2_AREA_MARINA="SELEZIONA UNA DELLE 27 AREE MARINE PROTETTE PER SAPERNE DI PIÙ";
export const IT = "it"
export const EN = "en"
export const FACILE = 1
export const FACILE_STRING = "FACILE"
export const INTERMEDIO = 2
export const INTERMEDIO_STRING = "INTERMEDIO"
export const DIFFICILE = 3
export const DIFFICILE_STRING = "DIFFICILE"
export const DIFFICILE_PLUS = 4
export const DIFFICILE_PLUS_STRING = "DIFFICILE +"
export const APERTO = 1
export const APERTO_STRING = "APERTO"
export const CHIUSO = 2
export const CHIUSO_STRING = "CHIUSO"
export const NESSUN_INFORMAZIONE_DISPONIBILE = "Nessun informazione disponibile"
export const PARCO_NAZIONALE = "PARCO NAZIONALE"
export const AREA_MARINA_PROTETTA = "AREA MARINA PROTETTA"
export const AREE_MARINE_PROTETTE="Aree Marine Protette"
export const PARCHI_E_AREE_PROTETTE="Parchi e aree protette"
export const AREA ="L'AREA"
export const IL_PARCO ="IL PARCO"
export const CONOSCI = "CONOSCI"
export const STORIA_GEOGRAFIA = "STORIA E GEOGRAFIA"
export const FLORA_FAUNA = "FLORA E FAUNA"
export const LUOGO = "Luogo"
export const CODICE = "Codice"
export const ENTE = "Ente gestore"
export const INDIRIZZO = "Indirizzo"
export const CONTATTI_DETT = "Contatti"
export const ESPLORA = "ESPLORA"
export const ITINERARI_DETT = "ITINERARI"
export const VISITA ="VISITA"
export const ITINERARIO="ITINERARIO"
export const VEDI_TUTTI_ITINERARI = "VEDI TUTTI GLI ITINERARI"
export const TESTO_REGIONI ="ESPLORA LE AREE NATURALI NELLE DIVERSE REGIONI ITALIANE"
export const ESPLORA_REGIONI ="Esplora regioni"
export const ESPLORA_ITINERARI ="Esplora itinerari"
export const SELEZIONA_PARCO_ITINERARI ="SELEZIONA IL PARCO NAZIONALE"
export const TESTO_ITINERARIO ="ESPLORA GLI ITINERARI NEI DIVERSI PARCHI NAZIONALI"
export const CERCA ="Cerca"
export const SELEZIONA_PARCO="Seleziona un parco"
